"""initial

Revision ID: 74aeef7c8731
Revises: 
Create Date: 2026-03-24 00:26:54.273022+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aeef7c8731'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'arena_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_public_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.drop_column('users', 'identity_statement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identity_statement', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_unique_constraint('users_public_id_key', 'users', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tasks', 'arena_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
